### ISSUE TITLE
Support generics for JSON variables

### ISSUE THREAD

**Issue by thawankeane** [KATT/envsafe#123]
Today the `json` validator returns `unknown` type, is there a reason for that?

Can we add support to generics to cover that gap?

AS-IS
```ts
const env = envsafe({
  CREDENTIALS: json(),
});

env.CREDENTIALS  // unknown 
``` 

TO-BE
```ts
const env = envsafe({
    CREDENTIALS: json<AppCredentials>(),
})

env.CREDENTIALS // AppCredentials
```

**Comment by KATT** [comment]
I won't add this as it won't actually validate that the json is legit. If you want something like this, you could probably use zod to validate the full structure

See comment here 0
