### ISSUE TITLE
question: can this be used for libraries?

### ISSUE THREAD

**Issue by jwyce** [KATT/envsafe#130]
Essentially the title. Should I be able to use this in a library so that if the consumer doesn't supply a required env var it will prompt them so (for instance in a next app). In my experimentation, it seems to work for one library, but when I add another to the mix it's unable to find a defined env variable... 🤔

**Comment by jwyce** [comment]
to give more context and a specific example: next-auth is a library that requires the NEXTAUTH_SECRET env variable or else it doesn't work. Sure I can check process.env and throw an error if it is undefined, but should envsafe be able to do that for free in my library?

I'll try to get a reproduction repo out there, but this situation I have now is a mono repo
|___ apps
|       |___ next.js
|___ packages
        |___ lib1
        |___ lib2

envsafe is being used in lib1 and lib2. seemingly lib 1 is working fine. there is a single env var required in both lib1 AND lib2 and lib2 is not detecting that it's in my .env in the next app. not sure if this is unintended behavior or if I'm trying to use envsafe for something it wasn't designed for, so would appreciate some feedback.

**Comment by KATT** [comment]
See https://github.com/KATT/envsafe/issues/107#issuecomment-1093112691

**Comment by KATT** [comment]
I'm not actively adding more features to envsafe
