### ISSUE TITLE
Not working on nextjs

### ISSUE THREAD

**Issue by bledar** [KATT/envsafe#148]
I am trying to setup envsafe in a NextJs project, but it is not working.
The values are printed in console, on the server side also client side but still the validation is showing them as missing.

### Printed value in NextJs dev server:
![image](https://github.com/KATT/envsafe/assets/4134276/76774df5-c118-403f-bea3-e39267169380)

### Browser console is showing the value and also the validation error.
![image](https://github.com/KATT/envsafe/assets/4134276/23c88d6d-bde4-4e6a-b56a-edde14127883)

### The validation code:
```js
import { str, envsafe, url, bool } from 'envsafe';

console.log('NEXT_PUBLIC_RUM_KEY' + process.env.NEXT_PUBLIC_RUM_KEY);

export const env = envsafe({
  NEXT_PUBLIC_RUM_KEY: str(),
});
```

Node version: **v16.18.1**
NextJs version: **13.2.4**

**Comment by boreyko1** [comment]
you should probably use `input` for next.js public variables as shown [here](https://github.com/KATT/envsafe/blob/f74736a24560f22cee5694d48546a247a47425bd/examples/next.js/utils/browserEnv.js#L6-L8)
